[package]
name = "brewdio-tui"
version = "0.2.4" # x-release-please-version
edition = "2021"

[[bin]]
name = "brewdio"
path = "src/main.rs"

[dependencies]
brewdio-core = { path = "../brewdio-core", features = ["crdt"] }
brewdio-persistence = { path = "../brewdio-persistence", features = ["native"] }
ratatui = "0.29"
crossterm = "0.28"
directories = "6"
rusqlite = { version = "0.34", features = ["bundled"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
tui-textarea = { version = "0.7.0", features = ["crossterm"] }
log = "0.4"
env_logger = "0.11"
