/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BreweryRouteImport } from './routes/brewery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as RecipesRecipeIdWaterRouteImport } from './routes/recipes.$recipeId_.water'
import { Route as RecipesRecipeIdMashRouteImport } from './routes/recipes.$recipeId_.mash'
import { Route as RecipesRecipeIdJsonRouteImport } from './routes/recipes.$recipeId_.json'
import { Route as RecipesRecipeIdBatchesRouteImport } from './routes/recipes.$recipeId_.batches'
import { Route as BatchesBatchIdWaterRouteImport } from './routes/batches.$batchId_.water'
import { Route as BatchesBatchIdMashRouteImport } from './routes/batches.$batchId_.mash'
import { Route as BatchesBatchIdJsonRouteImport } from './routes/batches.$batchId_.json'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BreweryRoute = BreweryRouteImport.update({
  id: '/brewery',
  path: '/brewery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdWaterRoute = RecipesRecipeIdWaterRouteImport.update({
  id: '/recipes/$recipeId_/water',
  path: '/recipes/$recipeId/water',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdMashRoute = RecipesRecipeIdMashRouteImport.update({
  id: '/recipes/$recipeId_/mash',
  path: '/recipes/$recipeId/mash',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdJsonRoute = RecipesRecipeIdJsonRouteImport.update({
  id: '/recipes/$recipeId_/json',
  path: '/recipes/$recipeId/json',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdBatchesRoute = RecipesRecipeIdBatchesRouteImport.update({
  id: '/recipes/$recipeId_/batches',
  path: '/recipes/$recipeId/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdWaterRoute = BatchesBatchIdWaterRouteImport.update({
  id: '/batches/$batchId_/water',
  path: '/batches/$batchId/water',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdMashRoute = BatchesBatchIdMashRouteImport.update({
  id: '/batches/$batchId_/mash',
  path: '/batches/$batchId/mash',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdJsonRoute = BatchesBatchIdJsonRouteImport.update({
  id: '/batches/$batchId_/json',
  path: '/batches/$batchId/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brewery': typeof BreweryRoute
  '/settings': typeof SettingsRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/batches/$batchId/json': typeof BatchesBatchIdJsonRoute
  '/batches/$batchId/mash': typeof BatchesBatchIdMashRoute
  '/batches/$batchId/water': typeof BatchesBatchIdWaterRoute
  '/recipes/$recipeId/batches': typeof RecipesRecipeIdBatchesRoute
  '/recipes/$recipeId/json': typeof RecipesRecipeIdJsonRoute
  '/recipes/$recipeId/mash': typeof RecipesRecipeIdMashRoute
  '/recipes/$recipeId/water': typeof RecipesRecipeIdWaterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brewery': typeof BreweryRoute
  '/settings': typeof SettingsRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/batches/$batchId/json': typeof BatchesBatchIdJsonRoute
  '/batches/$batchId/mash': typeof BatchesBatchIdMashRoute
  '/batches/$batchId/water': typeof BatchesBatchIdWaterRoute
  '/recipes/$recipeId/batches': typeof RecipesRecipeIdBatchesRoute
  '/recipes/$recipeId/json': typeof RecipesRecipeIdJsonRoute
  '/recipes/$recipeId/mash': typeof RecipesRecipeIdMashRoute
  '/recipes/$recipeId/water': typeof RecipesRecipeIdWaterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brewery': typeof BreweryRoute
  '/settings': typeof SettingsRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/batches/$batchId_/json': typeof BatchesBatchIdJsonRoute
  '/batches/$batchId_/mash': typeof BatchesBatchIdMashRoute
  '/batches/$batchId_/water': typeof BatchesBatchIdWaterRoute
  '/recipes/$recipeId_/batches': typeof RecipesRecipeIdBatchesRoute
  '/recipes/$recipeId_/json': typeof RecipesRecipeIdJsonRoute
  '/recipes/$recipeId_/mash': typeof RecipesRecipeIdMashRoute
  '/recipes/$recipeId_/water': typeof RecipesRecipeIdWaterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brewery'
    | '/settings'
    | '/batches/$batchId'
    | '/recipes/$recipeId'
    | '/batches/$batchId/json'
    | '/batches/$batchId/mash'
    | '/batches/$batchId/water'
    | '/recipes/$recipeId/batches'
    | '/recipes/$recipeId/json'
    | '/recipes/$recipeId/mash'
    | '/recipes/$recipeId/water'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brewery'
    | '/settings'
    | '/batches/$batchId'
    | '/recipes/$recipeId'
    | '/batches/$batchId/json'
    | '/batches/$batchId/mash'
    | '/batches/$batchId/water'
    | '/recipes/$recipeId/batches'
    | '/recipes/$recipeId/json'
    | '/recipes/$recipeId/mash'
    | '/recipes/$recipeId/water'
  id:
    | '__root__'
    | '/'
    | '/brewery'
    | '/settings'
    | '/batches/$batchId'
    | '/recipes/$recipeId'
    | '/batches/$batchId_/json'
    | '/batches/$batchId_/mash'
    | '/batches/$batchId_/water'
    | '/recipes/$recipeId_/batches'
    | '/recipes/$recipeId_/json'
    | '/recipes/$recipeId_/mash'
    | '/recipes/$recipeId_/water'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreweryRoute: typeof BreweryRoute
  SettingsRoute: typeof SettingsRoute
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  BatchesBatchIdJsonRoute: typeof BatchesBatchIdJsonRoute
  BatchesBatchIdMashRoute: typeof BatchesBatchIdMashRoute
  BatchesBatchIdWaterRoute: typeof BatchesBatchIdWaterRoute
  RecipesRecipeIdBatchesRoute: typeof RecipesRecipeIdBatchesRoute
  RecipesRecipeIdJsonRoute: typeof RecipesRecipeIdJsonRoute
  RecipesRecipeIdMashRoute: typeof RecipesRecipeIdMashRoute
  RecipesRecipeIdWaterRoute: typeof RecipesRecipeIdWaterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brewery': {
      id: '/brewery'
      path: '/brewery'
      fullPath: '/brewery'
      preLoaderRoute: typeof BreweryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId_/water': {
      id: '/recipes/$recipeId_/water'
      path: '/recipes/$recipeId/water'
      fullPath: '/recipes/$recipeId/water'
      preLoaderRoute: typeof RecipesRecipeIdWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId_/mash': {
      id: '/recipes/$recipeId_/mash'
      path: '/recipes/$recipeId/mash'
      fullPath: '/recipes/$recipeId/mash'
      preLoaderRoute: typeof RecipesRecipeIdMashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId_/json': {
      id: '/recipes/$recipeId_/json'
      path: '/recipes/$recipeId/json'
      fullPath: '/recipes/$recipeId/json'
      preLoaderRoute: typeof RecipesRecipeIdJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId_/batches': {
      id: '/recipes/$recipeId_/batches'
      path: '/recipes/$recipeId/batches'
      fullPath: '/recipes/$recipeId/batches'
      preLoaderRoute: typeof RecipesRecipeIdBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId_/water': {
      id: '/batches/$batchId_/water'
      path: '/batches/$batchId/water'
      fullPath: '/batches/$batchId/water'
      preLoaderRoute: typeof BatchesBatchIdWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId_/mash': {
      id: '/batches/$batchId_/mash'
      path: '/batches/$batchId/mash'
      fullPath: '/batches/$batchId/mash'
      preLoaderRoute: typeof BatchesBatchIdMashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId_/json': {
      id: '/batches/$batchId_/json'
      path: '/batches/$batchId/json'
      fullPath: '/batches/$batchId/json'
      preLoaderRoute: typeof BatchesBatchIdJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreweryRoute: BreweryRoute,
  SettingsRoute: SettingsRoute,
  BatchesBatchIdRoute: BatchesBatchIdRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  BatchesBatchIdJsonRoute: BatchesBatchIdJsonRoute,
  BatchesBatchIdMashRoute: BatchesBatchIdMashRoute,
  BatchesBatchIdWaterRoute: BatchesBatchIdWaterRoute,
  RecipesRecipeIdBatchesRoute: RecipesRecipeIdBatchesRoute,
  RecipesRecipeIdJsonRoute: RecipesRecipeIdJsonRoute,
  RecipesRecipeIdMashRoute: RecipesRecipeIdMashRoute,
  RecipesRecipeIdWaterRoute: RecipesRecipeIdWaterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
