use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::env;
use std::fs;
use std::path::PathBuf;
use syn::{parse_file, parse2, Fields, Item, Visibility};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir.join("../..");

    let source_files = [
        repo_root.join("brewdio-core/src/beerjson_types.rs"),
        repo_root.join("brewdio-core/src/equipment_profile.rs"),
        repo_root.join("brewdio-persistence/src/recipe.rs"),
        repo_root.join("brewdio-persistence/src/batch.rs"),
        repo_root.join("brewdio-persistence/src/settings.rs"),
    ];

    for path in &source_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!("cargo:rerun-if-changed=build.rs");

    let mut mirrors = TokenStream::new();
    let mut total_count = 0usize;

    for path in &source_files {
        let src = fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
        let ast = parse_file(&src)
            .unwrap_or_else(|e| panic!("Failed to parse {}: {}", path.display(), e));
        let filename = path.file_name().unwrap().to_str().unwrap();
        let count = generate_mirrors(&ast, &mut mirrors, filename);
        eprintln!(
            "cargo:warning=FRB mirrors: {} types from {}",
            count, filename
        );
        total_count += count;
    }

    if total_count == 0 {
        panic!("No types were mirrored — source files may have changed format");
    }

    let output = quote! {
        // DO NOT EDIT — auto-generated by build.rs
        // FRB mirror declarations for types from brewdio-core and brewdio-persistence.

        #![allow(dead_code, unexpected_cfgs)]

        use flutter_rust_bridge::frb;
        pub use brewdio_core::beerjson_types::*;
        pub use brewdio_core::equipment_profile::EquipmentProfile;
        pub use brewdio_persistence::batch::{Batch, BatchData};
        pub use brewdio_persistence::recipe::Recipe;
        pub use brewdio_persistence::settings::SettingsDocument;

        #mirrors
    };

    let syntax_tree =
        syn::parse2(output).expect("Failed to parse generated mirror code as valid Rust");
    let formatted = prettyplease::unparse(&syntax_tree);

    let dest = manifest_dir.join("src/frb_mirrors.rs");
    fs::write(&dest, formatted).expect("Failed to write frb_mirrors.rs");

    eprintln!(
        "cargo:warning=FRB mirrors: wrote {} total mirror declarations",
        total_count
    );

    // Run FRB codegen and patch Dart output, but only during direct `cargo build`.
    // Skip when Cargokit is driving the build (e.g. during `flutter build`).
    if env::var("CARGOKIT_MANIFEST_DIR").is_err() {
        run_frb_codegen(&manifest_dir);
    }
}

/// Generate mirror declarations for all public types found in a parsed file.
/// Returns the number of types mirrored.
fn generate_mirrors(ast: &syn::File, tokens: &mut TokenStream, filename: &str) -> usize {
    let mut count = 0;

    for item in &ast.items {
        match item {
            Item::Struct(s) if is_public(&s.vis) => {
                if has_lifetime_or_reference(s) {
                    continue;
                }
                if emit_struct_mirror(s, tokens, filename) {
                    count += 1;
                }
            }
            Item::Enum(e) if is_public(&e.vis) => {
                if has_lifetime_or_reference_enum(e) {
                    continue;
                }
                emit_enum_mirror(e, tokens, filename);
                count += 1;
            }

            // Macro invocations — extract struct/enum definitions from body
            Item::Macro(m) => {
                count += extract_from_macro(m, tokens, filename);
            }

            // Non-public items and implementations are expected
            Item::Struct(_) | Item::Enum(_) => {}
            Item::Impl(_) => {}
            Item::Mod(_) => {}
            Item::Use(_) => {}
            Item::Fn(_) => {}
            Item::Const(_) => {}
            Item::Static(_) => {}
            Item::Type(_) => {}

            other => {
                panic!(
                    "Unexpected item kind `{}` in {} — \
                     the build script may need updating",
                    item_kind_name(other),
                    filename
                );
            }
        }
    }

    count
}

/// Returns false if the struct was skipped (e.g. private newtype inner).
fn emit_struct_mirror(s: &syn::ItemStruct, tokens: &mut TokenStream, filename: &str) -> bool {
    let name = &s.ident;
    let mirror_name = format_ident!("_{}", name);

    match &s.fields {
        Fields::Named(fields) => {
            let pub_fields: Vec<_> = fields
                .named
                .iter()
                .filter(|f| is_public(&f.vis))
                .collect();
            if pub_fields.is_empty() {
                panic!(
                    "Struct `{}` in {} has named fields but none are public",
                    name, filename
                );
            }
            let field_defs: Vec<TokenStream> = pub_fields
                .iter()
                .map(|f| {
                    let fname = &f.ident;
                    let ftype = &f.ty;
                    quote! { pub #fname: #ftype, }
                })
                .collect();
            tokens.extend(quote! {
                #[frb(mirror(#name))]
                pub struct #mirror_name {
                    #(#field_defs)*
                }
            });
            true
        }
        Fields::Unnamed(fields) if fields.unnamed.len() == 1 => {
            if !is_public(&fields.unnamed[0].vis) {
                return false;
            }
            let inner = &fields.unnamed[0].ty;
            tokens.extend(quote! {
                #[frb(mirror(#name))]
                pub struct #mirror_name(pub #inner);
            });
            true
        }
        Fields::Unnamed(fields) => {
            panic!(
                "Unexpected multi-field tuple struct `{}` ({} fields) in {}",
                name,
                fields.unnamed.len(),
                filename
            );
        }
        Fields::Unit => {
            panic!("Unexpected unit struct `{}` in {}", name, filename);
        }
    }
}

fn emit_enum_mirror(e: &syn::ItemEnum, tokens: &mut TokenStream, filename: &str) {
    let name = &e.ident;
    let mirror_name = format_ident!("_{}", name);

    if e.variants.is_empty() {
        panic!("Enum `{}` in {} has no variants", name, filename);
    }

    let variant_defs: Vec<TokenStream> = e
        .variants
        .iter()
        .map(|v| {
            let vname = &v.ident;
            // FRB strips leading underscores when generating Dart names.
            // Variants like `_1` become `1` which is invalid in Dart.
            // Use #[frb(name = "N1")] to give them a valid Dart name
            // while keeping the original Rust variant name.
            let needs_rename = {
                let s = vname.to_string();
                s.starts_with('_') && s[1..].starts_with(|c: char| c.is_ascii_digit())
            };
            let rename_attr = if needs_rename {
                let dart_name = format!("n{}", &vname.to_string()[1..]);
                quote! { #[frb(name = #dart_name)] }
            } else {
                quote! {}
            };
            match &v.fields {
                Fields::Named(fields) => {
                    let field_defs: Vec<TokenStream> = fields
                        .named
                        .iter()
                        .map(|f| {
                            let fname = &f.ident;
                            let ftype = &f.ty;
                            quote! { #fname: #ftype }
                        })
                        .collect();
                    quote! { #rename_attr #vname { #(#field_defs,)* }, }
                }
                Fields::Unnamed(fields) => {
                    let types: Vec<&syn::Type> = fields.unnamed.iter().map(|f| &f.ty).collect();
                    quote! { #rename_attr #vname(#(#types),*), }
                }
                Fields::Unit => {
                    quote! { #rename_attr #vname, }
                }
            }
        })
        .collect();

    tokens.extend(quote! {
        #[frb(mirror(#name))]
        pub enum #mirror_name {
            #(#variant_defs)*
        }
    });
}

/// Extract public struct/enum definitions from macro invocations like `brewing_model! { ... }`.
fn extract_from_macro(
    m: &syn::ItemMacro,
    tokens: &mut TokenStream,
    filename: &str,
) -> usize {
    // Only process known macros
    let macro_name = m
        .mac
        .path
        .segments
        .last()
        .map(|s| s.ident.to_string())
        .unwrap_or_default();

    match macro_name.as_str() {
        "brewing_model" => {}
        other => {
            panic!(
                "Unexpected macro invocation `{}!` in {} — \
                 only `brewing_model!` is supported",
                other, filename
            );
        }
    }

    let body = &m.mac.tokens;
    let mut count = 0;

    // The macro body contains struct/enum definitions, possibly with extra attributes.
    // Try to parse as individual items.
    // First try as a single item:
    if let Ok(item) = parse2::<Item>(body.clone()) {
        match &item {
            Item::Struct(s) if is_public(&s.vis) => {
                if emit_struct_mirror(s, tokens, filename) {
                    count += 1;
                }
            }
            Item::Enum(e) if is_public(&e.vis) => {
                emit_enum_mirror(e, tokens, filename);
                count += 1;
            }
            _ => {
                panic!(
                    "brewing_model! in {} contains unexpected item: {}",
                    filename,
                    item_kind_name(&item)
                );
            }
        }
    } else {
        // Try wrapping in a module to parse multiple items
        let wrapped: TokenStream = quote! { mod _tmp { #body } };
        if let Ok(file) = syn::parse2::<syn::File>(wrapped) {
            for item in &file.items {
                if let Item::Mod(m) = item {
                    if let Some((_, items)) = &m.content {
                        for inner in items {
                            match inner {
                                Item::Struct(s) if is_public(&s.vis) => {
                                    if emit_struct_mirror(s, tokens, filename) {
                                        count += 1;
                                    }
                                }
                                Item::Enum(e) if is_public(&e.vis) => {
                                    emit_enum_mirror(e, tokens, filename);
                                    count += 1;
                                }
                                _ => {}
                            }
                        }
                    }
                }
            }
        } else {
            panic!(
                "Failed to parse brewing_model! body in {} — \
                 the macro format may have changed",
                filename
            );
        }
    }

    count
}

fn is_public(vis: &Visibility) -> bool {
    matches!(vis, Visibility::Public(_))
}

/// Check if a struct has lifetime parameters or reference fields.
fn has_lifetime_or_reference(s: &syn::ItemStruct) -> bool {
    if s.generics.lifetimes().count() > 0 {
        return true;
    }
    let code = quote!(#s).to_string();
    code.contains("& '") || code.contains("&'") || code.contains("& 'static")
}

fn has_lifetime_or_reference_enum(e: &syn::ItemEnum) -> bool {
    if e.generics.lifetimes().count() > 0 {
        return true;
    }
    let code = quote!(#e).to_string();
    code.contains("& '") || code.contains("&'")
}

fn item_kind_name(item: &Item) -> &'static str {
    match item {
        Item::Const(_) => "const",
        Item::Enum(_) => "enum",
        Item::ExternCrate(_) => "extern crate",
        Item::Fn(_) => "fn",
        Item::ForeignMod(_) => "foreign mod",
        Item::Impl(_) => "impl",
        Item::Macro(_) => "macro",
        Item::Mod(_) => "mod",
        Item::Static(_) => "static",
        Item::Struct(_) => "struct",
        Item::Trait(_) => "trait",
        Item::TraitAlias(_) => "trait alias",
        Item::Type(_) => "type alias",
        Item::Union(_) => "union",
        Item::Use(_) => "use",
        Item::Verbatim(_) => "verbatim",
        _ => "unknown",
    }
}

/// Run `flutter_rust_bridge_codegen generate` from the Flutter project root,
/// then patch the generated Dart to fix invalid enum variant names.
fn run_frb_codegen(manifest_dir: &PathBuf) {
    let flutter_root = manifest_dir.join("..");

    // Run FRB codegen
    let status = std::process::Command::new("flutter_rust_bridge_codegen")
        .arg("generate")
        .current_dir(&flutter_root)
        .status();

    match status {
        Ok(s) if s.success() => {
            eprintln!("cargo:warning=FRB codegen: success");
        }
        Ok(s) => {
            panic!(
                "flutter_rust_bridge_codegen exited with {}",
                s.code().unwrap_or(-1)
            );
        }
        Err(e) => {
            eprintln!("cargo:warning=FRB codegen: skipped (flutter_rust_bridge_codegen not found: {e})");
            return;
        }
    }

    // Patch frb_mirrors.dart: FRB v2.11.1 ignores #[frb(name)] on mirror enum
    // variants, so `_1` becomes the invalid Dart identifier `1`. Fix it to `n1`.
    let mirrors_dart = flutter_root.join("lib/src/rust/frb_mirrors.dart");
    if mirrors_dart.exists() {
        let content = fs::read_to_string(&mirrors_dart).expect("Failed to read frb_mirrors.dart");
        let patched = patch_enum_variant_names(&content);
        if patched != content {
            fs::write(&mirrors_dart, &patched).expect("Failed to write patched frb_mirrors.dart");
            eprintln!("cargo:warning=FRB codegen: patched invalid enum variant names in frb_mirrors.dart");
        }
    }

    // Run build_runner for freezed codegen.
    // Try `dart` first, fall back to `flutter pub run` (some CI setups only have flutter on PATH).
    let build_runner_status = std::process::Command::new("dart")
        .args(["run", "build_runner", "build", "--delete-conflicting-outputs"])
        .current_dir(&flutter_root)
        .status();

    let success = match &build_runner_status {
        Ok(s) if s.success() => true,
        Ok(_) | Err(_) => {
            // Fallback: try via flutter
            let fallback = std::process::Command::new("flutter")
                .args(["pub", "run", "build_runner", "build", "--delete-conflicting-outputs"])
                .current_dir(&flutter_root)
                .status();
            matches!(&fallback, Ok(s) if s.success())
        }
    };

    if success {
        eprintln!("cargo:warning=FRB codegen: build_runner success");
    } else {
        // This is fatal — without freezed codegen, Dart compilation will fail
        panic!(
            "build_runner failed — freezed codegen is required. \
             Ensure 'dart' or 'flutter' is on PATH and 'flutter pub get' has been run."
        );
    }
}

/// Fix enum variants that are bare numbers (invalid Dart identifiers).
/// E.g. inside `enum UnitUnitType { 1, unit, ... }` → `enum UnitUnitType { n1, unit, ... }`
fn patch_enum_variant_names(content: &str) -> String {
    let mut result = String::with_capacity(content.len());
    let mut in_enum = false;
    let mut brace_depth = 0u32;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("enum ") {
            in_enum = true;
            brace_depth = 0;
        }

        if in_enum {
            for ch in trimmed.chars() {
                match ch {
                    '{' => brace_depth += 1,
                    '}' => {
                        brace_depth = brace_depth.saturating_sub(1);
                        if brace_depth == 0 {
                            in_enum = false;
                        }
                    }
                    _ => {}
                }
            }

            // Check if the trimmed line is a bare numeric variant like `1,` or `123,`
            if in_enum || trimmed == "}" {
                let variant = trimmed.trim_end_matches(',');
                if !variant.is_empty() && variant.chars().all(|c| c.is_ascii_digit()) {
                    let indent = &line[..line.len() - trimmed.len()];
                    result.push_str(indent);
                    result.push('n');
                    result.push_str(trimmed);
                    result.push('\n');
                    continue;
                }
            }
        }

        result.push_str(line);
        result.push('\n');
    }

    // Preserve original trailing newline behavior
    if !content.ends_with('\n') && result.ends_with('\n') {
        result.pop();
    }

    result
}
