import type { RecipeType, EquipmentType, EquipmentProfile } from "brewdio-wasm";

// ---------------------------------------------------------------------------
// Typed document interfaces matching the Rust structs (generated by tsify)
// ---------------------------------------------------------------------------

export interface Recipe {
  id: string;
  name: string;
  recipe: RecipeType;
  equipment?: EquipmentType;
  equipmentId?: string;
}

export interface Batch {
  id: string;
  name: string;
  recipeId: string;
  data: BatchData;
}

export interface BatchData {
  equipmentId: string;
  recipe: RecipeType;
  equipment: EquipmentType;
  brewDate: number;
  notes?: string;
  createdAt: number;
  updatedAt: number;
}

export interface SettingsDocument {
  id: string;
  vimMode: boolean;
  defaultVolumeUnit: string;
  defaultMassUnit: string;
  defaultTemperatureUnit: string;
  openaiApiKey?: string;
  defaultAuthor?: string;
  aiBaseUrl?: string;
  aiModel?: string;
}

// ---------------------------------------------------------------------------
// DataBackend interface — enforced by the typechecker for both backends
// ---------------------------------------------------------------------------

export interface DataBackend {
  // Recipes
  listRecipes(): Promise<Recipe[]>;
  getRecipe(id: string): Promise<Recipe | null>;
  createRecipe(name: string, recipe: RecipeType, equipment?: EquipmentType, equipmentId?: string): Promise<string>;
  updateRecipe(id: string, name: string, recipe: RecipeType, equipment?: EquipmentType): Promise<void>;
  setRecipeEquipment(id: string, equipment?: EquipmentType, equipmentId?: string): Promise<void>;
  deleteRecipe(id: string): Promise<void>;

  // Batches
  listBatches(): Promise<Batch[]>;
  getBatch(id: string): Promise<Batch | null>;
  createBatch(name: string, recipeId: string, data: unknown): Promise<string>;
  updateBatch(id: string, name: string, data: unknown): Promise<void>;
  deleteBatch(id: string): Promise<void>;

  // Settings
  getSettings(): Promise<SettingsDocument | null>;
  saveSettings(data: SettingsDocument): Promise<void>;

  // Equipment Profiles
  listEquipmentProfiles(): Promise<EquipmentProfile[]>;
  createEquipmentProfile(profile: EquipmentProfile): Promise<string>;
  updateEquipmentProfile(id: string, profile: EquipmentProfile): Promise<void>;
  deleteEquipmentProfile(id: string): Promise<void>;

  // Change notifications
  onRecipesChange(cb: () => void): void;
  onBatchesChange(cb: () => void): void;
  onSettingsChange(cb: () => void): void;
  onEquipmentChange(cb: () => void): void;
}
