[package]
name = "brewdio-server"
version = "0.2.6" # x-release-please-version
edition = "2021"

[dependencies]
brewdio-persistence = { path = "../brewdio-persistence", features = ["native"] }
axum = { version = "0.8", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
futures-util = "0.3"
rusqlite = { version = "0.34", features = ["bundled"] }

[dev-dependencies]
brewdio-core = { path = "../brewdio-core" }
