/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as RecipesRecipeIdJsonRouteImport } from './routes/recipes.$recipeId_.json'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdJsonRoute = RecipesRecipeIdJsonRouteImport.update({
  id: '/recipes/$recipeId_/json',
  path: '/recipes/$recipeId/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/$recipeId/json': typeof RecipesRecipeIdJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/$recipeId/json': typeof RecipesRecipeIdJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/$recipeId_/json': typeof RecipesRecipeIdJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/recipes/$recipeId'
    | '/recipes/$recipeId/json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/recipes/$recipeId' | '/recipes/$recipeId/json'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/recipes/$recipeId'
    | '/recipes/$recipeId_/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesRecipeIdJsonRoute: typeof RecipesRecipeIdJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId_/json': {
      id: '/recipes/$recipeId_/json'
      path: '/recipes/$recipeId/json'
      fullPath: '/recipes/$recipeId/json'
      preLoaderRoute: typeof RecipesRecipeIdJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesRecipeIdJsonRoute: RecipesRecipeIdJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
